services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend/web_chatbot
    container_name: reactjs-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: alwaysd
